Point NSURL-IDN package to version using "-" instead of "+" (#24525)
This aims to address a validation error when the package is dynamically
linked, as introduced by
https://github.com/wordpress-mobile/WordPress-iOS/pull/24519

See TestFlight upload failure in
https://buildkite.com/automattic/wordpress-ios/builds/27601

> ERROR: [altool.600000D70180] Validation failed Invalid Info.plist value.
> The CFBundleExecutable Info.plist key contains the NSURL+IDN_-772325DC8649925D_PackageProduct value in the “Payload/Reader.app/Frameworks/NSURL+IDN_-772325DC8649925D_PackageProduct.framework” bundle.
> This key’s value can’t contain any of the following unsupported characters: \ [ ] { } ( ) + *